spring:
  application:
    name: Journal App

  data:
    mongodb:
      uri: mongodb+srv://devpanwar:qazxsw@cluster0.re3e6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      #if not created already...it will create one
      database: journaldb
      #for indexing in mongoDB...like we want to make a unique value
      auto-index-creation: true
      # Uncomment the following lines if you have a username and password
      # username: journaldb
      # password: journaldb

  main:
    allow-circular-references: true

server:
  port: 8080

# we can write any convention..like here we storing as weather.api.key
weather:
  api:
    key: 9007d5fb6a9cfc8498b9e20597d9e0fc

#we can also
#weather_api_key: 9007d5fb6a9cfc8498b9e20597d9e0fc

# when we don't use logback.xml for logging customizations...here we can set loggin levels for particular package also
#logging:
#  level:
#    com:
#      devpanwar:
#        journalApp: DEBUG
